### ISSUE TITLE
bitmasks

### ISSUE THREAD

**Issue by mmank** [kdn251/interviews#5]
Toggle kth bit: s ^= ~(1 << k)
should be
Toggle kth bit: s ^= (1 << k)

**Comment by kdn251** [comment]
Have it fixed for my next commit, thank you for pointing this out!

**Comment by Triang3l** [comment]
By the way, I'd also point out that compilers (not sure about the JVM though) seem to be much more likely to compile a `t = x; x = y; y = t;` sequence into a single `xchg` without the temporary variable (or with it, if used with memory rather than local variables likely to be mostly register-only, pure loads/stores) at all, though I'm not sure if it's still true today, but it also wouldn't work with floating-point numbers and is just harder to read. I'd add an "avoid it" (in favor of `std::swap`) warning to it.

**Comment by kdn251** [comment]
I believe you're right. I'll be sure to change it to 3 separate statements. Thank you!

**Comment by Triang3l** [comment]
I mean the whole idea is not recommended - and if asked in an interview, maybe it would be useful to mention its issues as well. But maybe not in case of JVM (though Android Runtime appears to be based on LLVM, so it's possible that common optimizations are done by it as well).
